package com.novbank.ndp.kernel.vocabulary;

import com.novbank.ndp.kernel.concept.RDFProperty;
import com.novbank.ndp.kernel.concept.RDFResource;
import com.novbank.ndp.kernel.concept.RDFVocabulary;

/**
 * Created by CaoKe on 2015/5/12.
 */
public class FOAF extends RDFVocabulary{
    public static final String NAMESPACE = "http://xmlns.com/foaf/0.1/";
    public static final String PREFIX = "foaf";
    public static final FOAF INSTANCE = new FOAF();

    public final RDFResource Agent;
    public final RDFResource Document;
    public final RDFResource Group;
    public final RDFResource Image;
    public final RDFResource LabelProperty;
    public final RDFResource OnlineAccount;
    public final RDFResource OnlineChatAccount;
    public final RDFResource OnlineEcommerceAccount;
    public final RDFResource OnlineGamingAccount;
    public final RDFResource Organization;
    public final RDFResource Person;
    public final RDFResource PersonalProfileDocument;
    public final RDFResource Project;

    public final RDFProperty account;
    public final RDFProperty accountName;
    public final RDFProperty accountServiceHomepage;
    public final RDFProperty age;
    public final RDFProperty aimChatID;
    public final RDFProperty based_near;
    public final RDFProperty birthday;
    public final RDFProperty currentProject;
    public final RDFProperty depiction;
    public final RDFProperty depicts;
    public final RDFProperty dnaChecksum;
    public final RDFProperty familyName;
    public final RDFProperty family_name;
    public final RDFProperty firstName;
    public final RDFProperty focus;
    public final RDFProperty fundedBy;
    public final RDFProperty geekcode;
    public final RDFProperty gender;
    public final RDFProperty givenName;
    public final RDFProperty givenname;
    public final RDFProperty holdsAccount;
    public final RDFProperty homepage;
    public final RDFProperty icqChatID;
    public final RDFProperty img;
    public final RDFProperty interest;
    public final RDFProperty isPrimaryTopicOf;
    public final RDFProperty jabberID;
    public final RDFProperty knows;
    public final RDFProperty lastName;
    public final RDFProperty logo;
    public final RDFProperty made;
    public final RDFProperty maker;
    public final RDFProperty mbox;
    public final RDFProperty mbox_sha1sum;
    public final RDFProperty member;
    public final RDFProperty membershipClass;
    public final RDFProperty msnChatID;
    public final RDFProperty myersBriggs;
    public final RDFProperty name;
    public final RDFProperty nick;
    public final RDFProperty openid;
    public final RDFProperty page;
    public final RDFProperty pastProject;
    public final RDFProperty phone;
    public final RDFProperty plan;
    public final RDFProperty primaryTopic;
    public final RDFProperty publications;
    public final RDFProperty schoolHomepage;
    public final RDFProperty sha1;
    public final RDFProperty skypeID;
    public final RDFProperty status;
    public final RDFProperty surname;
    public final RDFProperty theme;
    public final RDFProperty thumbnail;
    public final RDFProperty tipjar;
    public final RDFProperty title;
    public final RDFProperty topic;
    public final RDFProperty topic_interest;
    public final RDFProperty weblog;
    public final RDFProperty workInfoHomepage;
    public final RDFProperty workplaceHomepage;
    public final RDFProperty yahooChatID;


    public FOAF() {
        super(NAMESPACE,PREFIX);
        Agent = addClass("Agent");
        Document = addClass("Document");
        Group = addClass("Group");
        Image = addClass("Image");
        LabelProperty = addClass("LabelProperty");
        OnlineAccount = addClass("OnlineAccount");
        OnlineChatAccount = addClass("OnlineChatAccount");
        OnlineEcommerceAccount = addClass("OnlineEcommerceAccount");
        OnlineGamingAccount = addClass("OnlineGamingAccount");
        Organization = addClass("Organization");
        Person = addClass("Person");
        PersonalProfileDocument = addClass("PersonalProfileDocument");
        Project = addClass("Project");

        account = addProperty("account");
        accountName = addProperty("accountName");
        accountServiceHomepage = addProperty("accountServiceHomepage");
        age = addProperty("age");
        aimChatID = addProperty("aimChatID");
        based_near = addProperty("based_near");
        birthday = addProperty("birthday");
        currentProject = addProperty("currentProject");
        depiction = addProperty("depiction");
        depicts = addProperty("depicts");
        dnaChecksum = addProperty("dnaChecksum");
        familyName = addProperty("familyName");
        family_name = addProperty("family_name");
        firstName = addProperty("firstName");
        focus = addProperty("focus");
        fundedBy = addProperty("fundedBy");
        geekcode = addProperty("geekcode");
        gender = addProperty("gender");
        givenName = addProperty("givenName");
        givenname = addProperty("givenname");
        holdsAccount = addProperty("holdsAccount");
        homepage = addProperty("homepage");
        icqChatID = addProperty("icqChatID");
        img = addProperty("img");
        interest = addProperty("interest");
        isPrimaryTopicOf = addProperty("isPrimaryTopicOf");
        jabberID = addProperty("jabberID");
        knows = addProperty("knows");
        lastName = addProperty("lastName");
        logo = addProperty("logo");
        made = addProperty("made");
        maker = addProperty("maker");
        mbox = addProperty("mbox");
        mbox_sha1sum = addProperty("mbox_sha1sum");
        member = addProperty("member");
        membershipClass = addProperty("membershipClass");
        msnChatID = addProperty("msnChatID");
        myersBriggs = addProperty("myersBriggs");
        name = addProperty("name");
        nick = addProperty("nick");
        openid = addProperty("openid");
        page = addProperty("page");
        pastProject = addProperty("pastProject");
        phone = addProperty("phone");
        plan = addProperty("plan");
        primaryTopic = addProperty("primaryTopic");
        publications = addProperty("publications");
        schoolHomepage = addProperty("schoolHomepage");
        sha1 = addProperty("sha1");
        skypeID = addProperty("skypeID");
        status = addProperty("status");
        surname = addProperty("surname");
        theme = addProperty("theme");
        thumbnail = addProperty("thumbnail");
        tipjar = addProperty("tipjar");
        title = addProperty("title");
        topic = addProperty("topic");
        topic_interest = addProperty("topic_interest");
        weblog = addProperty("weblog");
        workInfoHomepage = addProperty("workInfoHomepage");
        workplaceHomepage = addProperty("workplaceHomepage");
        yahooChatID = addProperty("yahooChatID");
    }

    public static final RDFResource AGENT = INSTANCE.Agent;
    public static final RDFResource DOCUMENT = INSTANCE.Document;
    public static final RDFResource GROUP = INSTANCE.Group;
    public static final RDFResource IMAGE = INSTANCE.Image;
    public static final RDFResource LABEL_PROPERTY = INSTANCE.LabelProperty;
    public static final RDFResource ONLINE_ACCOUNT = INSTANCE.OnlineAccount;
    public static final RDFResource ONLINE_CHAT_ACCOUNT = INSTANCE.OnlineChatAccount;
    public static final RDFResource ONLINE_ECOMMERCE_ACCOUNT = INSTANCE.OnlineEcommerceAccount;
    public static final RDFResource ONLINE_GAMING_ACCOUNT = INSTANCE.OnlineGamingAccount;
    public static final RDFResource ORGANIZATION = INSTANCE.Organization;
    public static final RDFResource PERSON = INSTANCE.Person;
    public static final RDFResource PERSONAL_PROFILE_DOCUMENT = INSTANCE.PersonalProfileDocument;
    public static final RDFResource PROJECT = INSTANCE.Project;


    public static final RDFProperty ACCOUNT = INSTANCE.account;
    public static final RDFProperty ACCOUNT_NAME = INSTANCE.accountName;
    public static final RDFProperty ACCOUNT_SERVICE_HOMEPAGE = INSTANCE.accountServiceHomepage;
    public static final RDFProperty AGE = INSTANCE.age;
    public static final RDFProperty AIM_CHAT_ID = INSTANCE.aimChatID;
    public static final RDFProperty BASED_NEAR = INSTANCE.based_near;
    public static final RDFProperty BIRTHDAY = INSTANCE.birthday;
    public static final RDFProperty CURRENT_PROJECT = INSTANCE.currentProject;
    public static final RDFProperty DEPICTION = INSTANCE.depiction;
    public static final RDFProperty DEPICTS = INSTANCE.depicts;
    public static final RDFProperty FAMILY_NAME = INSTANCE.familyName;
    public static final RDFProperty FIRST_NAME = INSTANCE.firstName;
    public static final RDFProperty FOCUS = INSTANCE.focus;
    public static final RDFProperty GENDER = INSTANCE.gender;
    public static final RDFProperty GIVEN_NAME = INSTANCE.givenName;
    public static final RDFProperty HOMEPAGE = INSTANCE.homepage;
    public static final RDFProperty ICQ_CHAT_ID = INSTANCE.icqChatID;
    public static final RDFProperty IMG = INSTANCE.img;
    public static final RDFProperty INTEREST = INSTANCE.interest;
    public static final RDFProperty IS_PRIMARY_TOPIC_OF = INSTANCE.isPrimaryTopicOf;
    public static final RDFProperty JABBER_ID = INSTANCE.jabberID;
    public static final RDFProperty KNOWS = INSTANCE.knows;
    public static final RDFProperty LAST_NAME = INSTANCE.lastName;
    public static final RDFProperty LOGO = INSTANCE.logo;
    public static final RDFProperty MADE = INSTANCE.made;
    public static final RDFProperty MAKER = INSTANCE.maker;
    public static final RDFProperty MBOX = INSTANCE.mbox;
    public static final RDFProperty MBOX_SHA1SUM = INSTANCE.mbox_sha1sum;
    public static final RDFProperty MEMBER = INSTANCE.member;
    public static final RDFProperty MEMBERSHIP_CLASS = INSTANCE.membershipClass;
    public static final RDFProperty MSN_CHAT_ID = INSTANCE.msnChatID;
    public static final RDFProperty MYERS_BRIGGS = INSTANCE.myersBriggs;
    public static final RDFProperty NAME = INSTANCE.name;
    public static final RDFProperty NICK = INSTANCE.nick;
    public static final RDFProperty OPEN_ID = INSTANCE.openid;
    public static final RDFProperty PAGE = INSTANCE.page;
    public static final RDFProperty PAST_PROJECT = INSTANCE.pastProject;
    public static final RDFProperty PHONE = INSTANCE.phone;
    public static final RDFProperty PLAN = INSTANCE.plan;
    public static final RDFProperty PRIMARY_TOPIC = INSTANCE.primaryTopic;
    public static final RDFProperty PUBLICATIONS = INSTANCE.publications;
    public static final RDFProperty SCHOOL_HOMEPAGE = INSTANCE.schoolHomepage;
    public static final RDFProperty SHA1 = INSTANCE.sha1;
    public static final RDFProperty SKYPE_ID = INSTANCE.skypeID;
    public static final RDFProperty STATUS = INSTANCE.status;
    public static final RDFProperty THUMBNAIL = INSTANCE.thumbnail;
    public static final RDFProperty TIPJAR = INSTANCE.tipjar;
    public static final RDFProperty TITLE = INSTANCE.title;
    public static final RDFProperty TOPIC = INSTANCE.topic;
    public static final RDFProperty TOPIC_INTEREST = INSTANCE.topic_interest;
    public static final RDFProperty WEBLOG = INSTANCE.weblog;
    public static final RDFProperty WORKINFO_HOMEPAGE = INSTANCE.workInfoHomepage;
    public static final RDFProperty WORKPLACE_HOMEPAGE = INSTANCE.workplaceHomepage;
    public static final RDFProperty YAHOO_CHAT_ID = INSTANCE.yahooChatID;

}
